const BINANCE_BASE = 'https://api.binance.com'

export const TOP_PAIRS = [
  // Top Major
  'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT',
  'ADAUSDT','DOGEUSDT','AVAXUSDT','DOTUSDT','MATICUSDT',
  'LINKUSDT','LTCUSDT','UNIUSDT','ATOMUSDT','ETCUSDT',
  'XLMUSDT','NEARUSDT','ALGOUSDT','APTUSDT','FILUSDT',
  'ARBUSDT','OPUSDT','INJUSDT','SUIUSDT','SEIUSDT',
  'TIAUSDT','WLDUSDT','FETUSDT','GRTUSDT','SANDUSDT',
  'MANAUSDT','APEUSDT','AAVEUSDT','MKRUSDT','SNXUSDT',
  'COMPUSDT','CRVUSDT','RUNEUSDT','FTMUSDT','HBARUSDT',
  'EGLDUSDT','FLOWUSDT','ICPUSDT','VETUSDT','THETAUSDT',
  'QNTUSDT','KSMUSDT','ZECUSDT','ONEUSDT','ROSEUSDT',
  // DeFi
  'SUSHIUSDT','YFIUSDT','BALUSDT','KNCUSDT','BANDUSDT',
  'ANKRUSDT','SKLUSDT','STORJUSDT','IOTAUSDT','TRXUSDT',
  'EOSUSDT','XTZUSDT','ZENUSDT','ICXUSDT','IOSTUSDT',
  'ONTUSDT','NEOUSDT','XMRUSDT','DASHUSDT','WAVESUSDT',
  'ZILUSDT','BATUSDT','ENJUSDT','CHZUSDT','GALAUSDT',
  // Gaming & NFT
  'AXSUSDT','SLPUSDT','RAREUSDT','NFTUSDT','ELFUSDT',
  'ALICEUSDT','TLMUSDT','ALPACAUSDT','DYDXUSDT','IMXUSDT',
  'GMTUSDT','STEPNUSDT','MAGICUSDT','RNDRUSDT','HIGHUSDT',
  'STXUSDT','CFXUSDT','WOOUSDT','ACHUSDT','IDUSDT',
  // Layer 1 & 2
  'KASUSDT','TONUSDT','MOVEUSDT','EIGENUSDT','MEWUSDT',
  'NOTUSDT','DOGSUSDT','HMSTRUSDT','CATUSDT','BANANAUSDT',
  'TURBOUSDT','MEMEUSDT','PEPEUSDT','SHIBUSDT','FLOKIUSDT',
  'BONKUSDT','WIFUSDT','BOMEUSDT','SAFEUSDT','TAIKOUSDT',
  // Mid Cap
  'LRCUSDT','COTIUSDT','CTSIUSDT','TRUUSDT','BONDUSDT',
  'LPTUSDT','ACHUSDT','PERPUSDT','RGTUSDT','BADGERUSDT',
  'DIAUSDT','LINAUSDT','LITUSDT','POLSUSDT','DEXEUSDT',
  'ALPHAAUSDT','PRQUSDT','GTCUSDT','FARMUSDT','RARUSDT',
  'IDEXUSDT','COVERUSDT','PICKLEUSDT','POWRUSDT','AUDIOUSDT',
  'CELRUSDT','DENTUSDT','HOTUSDT','VETUSDT','WINUSDT',
  'SUNUSDT','BTTUSDT','JSTUSDT','NKNUSDT','SCUSDT',
  'DGBUSDT','RVNUSDT','MTLUSDT','STMXUSDT','RIFUSDT',
  'AKROUSDT','CTKUSDT','HARDUSDT','UNFIUSDT','OXTUSDT',
  'PAXGUSDT','RLCUSDT','MDTUSDT','DOCKUSDT','PERLUSDT',
  // New & Trending
  'PYTHUSDT','JUPUSDT','JITOUSDT','WUSDT','STRKUSDT',
  'ALTUSDT','DYMUSDT','PIXELUSDT','PORTALUSDT','AIUSDT',
  'MANTAUSDT','ZKUSDT','ZROUSDT','LISTAUSDT','IOUSDT',
  'REZUSDT','ENAUSDT','MERLINUSDT','SAGAUSDT','OMNIUSDT',
  'VANRYUSDT','ATAUSDT','BIOXUSDT','AEVOUSDT','PDAUSDT',
  // More Alts
  'HFTUSDT','PHBUSDT','AMBUSDT','HOOKUSDT','MAGAUSDT',
  'RDNTUSDT','UFTUSDT','LQTYUSDT','CVXUSDT','FXSUSDT',
  'FRAXUSDT','LDOUSDT','RPLUSDT','SSVUSDT','OMUSDT',
  'PENDLEUSDT','TRBUSDT','UMAUSDT','BLZUSDT','AGIXUSDT',
  'OCEANUSDT','NMRUSDT','RNDROUSDT','VRUSDT','CTXCUSDT',
  'STGUSDT','WOMBATUSDT','ARBUSDT','GMXUSDT','GNSUSDT',
  'CAPUSDT','LEVUSDT','KWENTAUSDT','SXUSDT','JASMYUSDT',
  'MDAUSDT','KLAYUSDT','CYBERUSDT','ARKMUSDT','ORDIUSDT',
  'SATSUSDT','RATS0USDT','MERCHUSDT','MULTIUSDT','XAIUSDT',
  'RONINUSDT','RONUSDT','ACEUSDT','NFPUSDT','AIUSDT',
  'COSUSDT','ONGUSDT','GASUSDT','NULSUSDT','WNXMUSDT'
]

export async function fetchKlines(symbol, interval = '30m', limit = 100) {
  const url = `${BINANCE_BASE}/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=${limit}`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Binance error: ${res.status}`)
  const data = await res.json()
  if (!Array.isArray(data) || data.length < 40) throw new Error(`Not enough data`)
  return {
    opens:  data.map(k => parseFloat(k[1])),
    highs:  data.map(k => parseFloat(k[2])),
    lows:   data.map(k => parseFloat(k[3])),
    closes: data.map(k => parseFloat(k[4])),
  }
}

export async function fetchPrice(symbol) {
  const url = `${BINANCE_BASE}/api/v3/ticker/price?symbol=${symbol}`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Price fetch error`)
  const json = await res.json()
  return parseFloat(json.price)
  }
  
